---
title: "Indicator Scoping"
editor: visual
---

## Compiling ideas

If you think of ideas for a new metric or someone you talk to suggests a metric, go to the issues tab and create a new issue. Use the "Metric Idea Form" issue template. Fill out as much information as you can, leaving entries blank as needed. Anyone can fill this form out with an idea. If you already know the data do not exist or are extremely limited, you can note that. You should ideally know where the data exist so you can note that on the form before we decide to include the metric. If you identify data online, you should test that it can be downloaded and everything looks kosher. If you need to run any code just to check/download the data and take a preliminary look at what it is, you can make a script and put it in the sandbox/prelim_code folder. Make sure to link the script/code in the comments of the metric idea issue corresponding to that metric.

::: callout-important
When you've finished filling out the Metric Idea Form, make sure you assign that issue to the "Indicator scoping xxx" project, so it automatically adds an entry to the project board.
:::

## Metric selection

Once the project board is filled with ideas and the appropriate people / teams have been consulted about metric ideas, the IEA team will meet to go over the list of metric ideas and decide which ones to include in the ESR and which ones not to. By the end of this meeting, all the metrics that will be included will have the selected category changed to "yes", everything else will be changed to "no" if the metric is not going to be used in the current report. Also, each metric will be assigned to an IEA POC by the end of the meeting. Make sure a root name has been created for each metric and documented in the project.